######################################################################
# Automatically generated by qmake (3.1) Fri Aug 22 17:53:32 2025
######################################################################

TEMPLATE = app
TARGET = 03designerDialog
QT += widgets
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp gotocellmain.cpp
