######################################################################
# Automatically generated by qmake (3.1) Mon Sep 1 16:25:04 2025
######################################################################

TEMPLATE = app
TARGET = qMWByCode
QT += widgets
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += cell.h \
           finddialog.h \
           gotocelldialog.h \
           mwbycode.h \
           sortdialog.h \
           spreadsheet.h \
           ui_gotocelldialog.h \
           ui_sortdialog.h
FORMS += gotocelldialog.ui sortdialog.ui
SOURCES += cell.cpp \
           finddialog.cpp \
           gotocelldialog.cpp \
           main.cpp \
           mwbycode.cpp \
           sortdialog.cpp \
           spreadsheet.cpp \
           release/qrc_spreadsheet.cpp
RESOURCES += spreadsheet.qrc
